services:
  ghost:
    image: ghost:6-alpine
    container_name: ghost
    restart: unless-stopped
    ports:
      - "2368:2368"
    depends_on:
      - db
    environment:
      url: http://localhost:2368
      database__client: mysql
      database__connection__host: db
      database__connection__user: ghostuser
      database__connection__password: ghostpass
      database__connection__database: ghostdb
      NODE_ENV: development
      security__staffDeviceVerification: false
    volumes:
      - ./ghost-content:/var/lib/ghost/content:cached  # For Mac with better performance

  db:
    image: mysql:8.0
    container_name: ghost-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ghostdb
      MYSQL_USER: ghostuser
      MYSQL_PASSWORD: ghostpass
    volumes:
      - ./ghost-db:/var/lib/mysql